### ISSUE TITLE
An Example of using the mesh maze plugin

### ISSUE THREAD

**Issue by gryff1000** [elfnor/mesh_maze#13]
Not really an "issue",  I used this plugin (Blender 3.2 version) to create mazes for the Babylon.js libraries. You can find the thread on the Babyloin.js forum here : https://forum.babylonjs.com/t/creating-mazes-with-blender-and-bjs-update-3/43875 .

It is the first post in a thread about creating mazes. I use Blender v3.3  and the add on loads with a warning that it might not work.  It does basically work, but it would be nice to have an updated version

You will notice that the SVG method allows a solution to be created which would be a nice feature.

You will see from the above thread link that I am "gryff". I hope it makes some Blender users aware of this plug in.

**Comment by elfnor** [comment]
Great to see my add-on in action.

I've just bumped the Blender version number to 3.6.0 and it all seems to be working. 

I thought  about adding a solve path, the math/code part is OK, but I couldn't come up with an easy interface for the user to mark start and end points.
