### ISSUE TITLE
v3.6 doesn't install on Blender 4.1

### ISSUE THREAD

**Issue by StefanoCecere** [elfnor/mesh_maze#14]
this is the error:
![Screenshot 2024-06-22 at 10 18 07](https://github.com/elfnor/mesh_maze/assets/640536/cf1a1d9c-e49b-4949-b6da-94e358dbfd3c)

**Comment by elfnor** [comment]
This seems to be a problem with the current release file. I downloaded the zip from the "Code" button and that one worked for me in Blender 4.1.0.

![image](https://github.com/elfnor/mesh_maze/assets/7930130/bad96fdf-7b90-47ae-9a15-aa73fca43704)

I'll replace the release version with the working version.

**Comment by elfnor** [comment]
Works for me here on 4.1.0 and 4.1.1 on Linux
