### ISSUE TITLE
Cannot install from release zip

### ISSUE THREAD

**Issue by vgf89** [elfnor/mesh_maze#7]
The name of the mesh_maze-2.90.0 folder inside the zip makes the blender addon utility look for a module called "mesh_maze-2" which fails. I had to rename the folder inside the zip to mesh_maze to make it install.

I'm on Blender 2.90.1 on Windows

**Comment by Nyarlukhotep** [comment]
Similar problem

**Comment by Twippster** [comment]
I had to extract it, and then I renamed it, but then i zipped it up again, and then when I tried installing the addon into blender, I don't see anything.

**Comment by elfnor** [comment]
Agreed, Github sets the name of the release file, I'll look into it.
In the meantime, downloading the zip file from the code button  gives a file `mesh_maze-master.zip` which does install OK.
It appears on the Mesh Menu in edit mode, and works in 2.91.0.

**Comment by elfnor** [comment]
Fixed by adding the zip file with no version number to the release.
