### ISSUE TITLE
Blender throwing TypeErrors when using the maze mesh

### ISSUE THREAD

**Issue by burnie5749** [elfnor/mesh_maze#8]
I have just installed your mesh maze maker into blender and tried to use it the way it says to use it on your GitHub page. The error message is TypeError: list indices must be integers or slices, not NoneType

is there something wrong with the way I installed the program or is the program I am using outdated? even though I am using blender 2.90.1
 I have added a screencap of the error.
![Errormsg](https://user-images.githubusercontent.com/46714025/98594405-85e54500-22cc-11eb-9571-38eb45a1b509.png)

**Comment by KiriNoMizumi** [comment]
Did you remember to _**subdivide**_ your mesh object?
Similar error happened when I forgot to _**subdivide**_ my mesh object.

**Comment by burnie5749** [comment]
That is my problem, Thank you for the help!
